parser: babel-eslint

extends:
  - airbnb

globals:
  console: false
  document: false
  window: false
  Exception: false
  WebSocket: false

rules:
  react/jsx-filename-extension: 'off'
  react/prefer-stateless-function: 'warn'
