language: go

go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - master

env:
  - TRAVIS_NODE_VERSION=8 GO111MODULE=on

before_install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install -g yarn
  - yarn install

script:
  - |
    for d in $(go list ./... | grep -Ev "vendor|assets|node_modules|docs"); do
        go test -v -race -coverprofile=profile.out -covermode=atomic $d
        if [ -f profile.out ]; then
            cat profile.out >> coverage.txt
            rm profile.out
        fi
    done
  - yarn test:js
