package assets

import (
	"github.com/go-serve/bindatafs"
)

// FileSystem returns a Filesystem implementation for the given assets
func FileSystem() bindatafs.FileSystem {
	// assume you have Asset, AssetDir, AssetInfo are generated by go-bindata
	return bindatafs.New("assets://", Asset, AssetDir, AssetInfo)
}
